@Library('jenkins-shared-lib') _

pipeline {
    agent { label 'ssh-agent-with-docker' }

    environment {
        CCACHE_PATH = "/home/administrator/.cache/ccache"
    }

    stages {
        stage('Build AOSP') {
            steps {
                buildAosp(
                        ccachePath: env.CCACHE_PATH,
                        dockerImage: 'aosp-builder',
                        sshCredential: 'gerrit-ssh-maksonlee',
                        manifestUrl: 'ssh://maksonlee@gerrit.maksonlee.com:29418/platform/manifest',
                        branch: 'android-15.0.0_r30',
                        lunchTarget: 'aosp_arm64-trunk_staging-userdebug'
                )
            }
        }

        stage('Deploy to Artifactory') {
            steps {
                uploadArtifacts(
                        orgPath: 'com/maksonlee',
                        module: '1234',
                        baseRev: '003-vanilla-continuous',
                        folderItegRev: 'SNAPSHOT',
                        repo: 'product-snapshots',
                        artifacts: [
                                [pattern: 'out/target/product/generic_arm64/system.img', classifier: 'system', ext: 'img'],
                                [pattern: 'out/target/product/generic_arm64/vbmeta.img', classifier: 'vbmeta', ext: 'img'],
                                [pattern: 'out/target/product/generic_arm64/ramdisk.img', classifier: 'ramdisk', ext: 'img'],
                        ]
                )
            }
        }
    }
}